from typing import TypedDict, Any, List, Dict

class CellAgentState(TypedDict):
    # User Inputs
    query: str
    dataset_path: str

    tools_registry: List[Dict[str, Any]]
    
    # Dataset Context & Data
    adata: Any  # The actual AnnData object
    dataset_metadata: Dict[str, Any]  # The extracted context/metadata
    
    # Planner Output
    planner_output: List[str]  # e.g., A list of subtasks/steps generated by the planner
    current_task_index: int
    current_task: Dict[str, Any]

    tool_info : Dict[str,Any]

    # Code programmer and notebook sandbox state.  `global_code_memory` is
    # replayed in each fresh execution kernel; `local_memory` only holds retry
    # feedback for the current or recent failed attempts.
    code_proposal: Dict[str, Any]
    global_code_memory: List[Dict[str, Any]]
    local_memory: List[Dict[str, Any]]
    sandbox_bootstrap_code: str
    sandbox_result: Dict[str, Any]
    artifact_dir: str
    sandbox_timeout_seconds: int
    project_root: str
    final_annotation_output: Dict[str, Any]
    visualization_output: Dict[str, Any]
    evaluator_input: Dict[str, Any]
    evaluator_output: Dict[str, Any]
    final_labels: Dict[str, str]
