from typing import TypedDict, Any, List, Dict

class CellAgentState(TypedDict):
    # User Inputs
    query: str
    dataset_path: str

    tools_registry: List[Dict[str, Any]]
    
    # Dataset Context & Data
    adata: Any  # The actual AnnData object
    dataset_metadata: Dict[str, Any]  # The extracted context/metadata
    
    # Planner Output
    planner_output: List[str]  # e.g., A list of subtasks/steps generated by the planner